### ISSUE TITLE
error in the norm_p function

### ISSUE THREAD

**Issue by qdesmedt** [dganguli/robust-pca#3]
```
@staticmethod
def norm_p(M, p):
     return np.sum(np.power(M, p))
```

That should not be:

```
@staticmethod
def norm_p(M, p):
    return np.power(
           np.sum(np.power(M, p)),
           1./p
     )
```

**Comment by Hisairnessag3** [comment]
where'd you even see this? Code hasn't been updated in over a year, and I see the top one in the repo

**Comment by muzammil360** [comment]
@qdesmedt, I agree with you. Infact, you should apply `abs(M)` as well before taking power `p`.

**Comment by dganguli** [comment]
thanks @qdesmedt and @muzammil360 you are both absolutely correct!

I think a better approach here is to simply use numpy to compute the frobenius norm:

```
np.linalg.norm(M, ord='fro')
```

which works as both of you expect
```
import numpy as np


def norm_p(M, p):
    return np.power(
           np.sum(np.power(np.abs(M), p)),
           1./p
     )

M = np.array([[1, -2, 3, 4], [5, -6, 7, 8]])
p = 2

print(norm_p(M,p))
print(np.linalg.norm(M, ord='fro'))

14.2828568570857
14.2828568570857
```

i can submit a pull request if one of you would like to review? thanks!

**Comment by dganguli** [comment]
here's the PR: 

https://github.com/dganguli/robust-pca/pull/5
